/**
 * مفاتيح الاتصال الدولية لكل الدول (للاختيار قبل رقم الجوال عند التسجيل).
 * الترتيب: السعودية ودول الخليج والعرب أولاً (الأكثر استخداماً) ثم بقية الدول.
 * علم الدولة يُشتق من رمز ISO عند العرض (flagEmoji) فلا حاجة لتخزينه.
 */
export interface Country {
  code: string // ISO 3166-1 alpha-2
  dial: string // مفتاح الاتصال (بدون +)
  name: string // الاسم بالعربية
}

/** يحوّل رمز الدولة (حرفان) إلى علم Emoji عبر رموز المؤشّر الإقليمي. */
export function flagEmoji(code: string): string {
  if (!code || code.length !== 2) return '🏳️'
  return code
    .toUpperCase()
    .replace(/./g, c => String.fromCodePoint(127397 + c.charCodeAt(0)))
}

// دول ذات أولوية (تظهر أولاً)
const PRIORITY: Country[] = [
  { code: 'SA', dial: '966', name: 'السعودية' },
  { code: 'AE', dial: '971', name: 'الإمارات' },
  { code: 'KW', dial: '965', name: 'الكويت' },
  { code: 'QA', dial: '974', name: 'قطر' },
  { code: 'BH', dial: '973', name: 'البحرين' },
  { code: 'OM', dial: '968', name: 'عُمان' },
  { code: 'EG', dial: '20', name: 'مصر' },
  { code: 'JO', dial: '962', name: 'الأردن' },
  { code: 'IQ', dial: '964', name: 'العراق' },
  { code: 'YE', dial: '967', name: 'اليمن' },
  { code: 'SY', dial: '963', name: 'سوريا' },
  { code: 'LB', dial: '961', name: 'لبنان' },
  { code: 'PS', dial: '970', name: 'فلسطين' },
  { code: 'SD', dial: '249', name: 'السودان' },
  { code: 'LY', dial: '218', name: 'ليبيا' },
  { code: 'TN', dial: '216', name: 'تونس' },
  { code: 'DZ', dial: '213', name: 'الجزائر' },
  { code: 'MA', dial: '212', name: 'المغرب' },
  { code: 'MR', dial: '222', name: 'موريتانيا' },
  { code: 'SO', dial: '252', name: 'الصومال' },
  { code: 'DJ', dial: '253', name: 'جيبوتي' },
  { code: 'KM', dial: '269', name: 'جزر القمر' },
]

// بقية دول العالم (مرتّبة أبجدياً بالعربية)
const REST: Country[] = [
  { code: 'AF', dial: '93', name: 'أفغانستان' },
  { code: 'AL', dial: '355', name: 'ألبانيا' },
  { code: 'DE', dial: '49', name: 'ألمانيا' },
  { code: 'AD', dial: '376', name: 'أندورا' },
  { code: 'AO', dial: '244', name: 'أنغولا' },
  { code: 'AI', dial: '1264', name: 'أنغويلا' },
  { code: 'AG', dial: '1268', name: 'أنتيغوا وباربودا' },
  { code: 'AR', dial: '54', name: 'الأرجنتين' },
  { code: 'AM', dial: '374', name: 'أرمينيا' },
  { code: 'AW', dial: '297', name: 'أروبا' },
  { code: 'AU', dial: '61', name: 'أستراليا' },
  { code: 'AT', dial: '43', name: 'النمسا' },
  { code: 'AZ', dial: '994', name: 'أذربيجان' },
  { code: 'BS', dial: '1242', name: 'الباهاما' },
  { code: 'BD', dial: '880', name: 'بنغلاديش' },
  { code: 'BB', dial: '1246', name: 'باربادوس' },
  { code: 'BY', dial: '375', name: 'بيلاروسيا' },
  { code: 'BE', dial: '32', name: 'بلجيكا' },
  { code: 'BZ', dial: '501', name: 'بليز' },
  { code: 'BJ', dial: '229', name: 'بنين' },
  { code: 'BM', dial: '1441', name: 'برمودا' },
  { code: 'BT', dial: '975', name: 'بوتان' },
  { code: 'BO', dial: '591', name: 'بوليفيا' },
  { code: 'BA', dial: '387', name: 'البوسنة والهرسك' },
  { code: 'BW', dial: '267', name: 'بوتسوانا' },
  { code: 'BR', dial: '55', name: 'البرازيل' },
  { code: 'BN', dial: '673', name: 'بروناي' },
  { code: 'BG', dial: '359', name: 'بلغاريا' },
  { code: 'BF', dial: '226', name: 'بوركينا فاسو' },
  { code: 'BI', dial: '257', name: 'بوروندي' },
  { code: 'CV', dial: '238', name: 'الرأس الأخضر' },
  { code: 'KH', dial: '855', name: 'كمبوديا' },
  { code: 'CM', dial: '237', name: 'الكاميرون' },
  { code: 'CA', dial: '1', name: 'كندا' },
  { code: 'KY', dial: '1345', name: 'جزر كايمان' },
  { code: 'CF', dial: '236', name: 'أفريقيا الوسطى' },
  { code: 'TD', dial: '235', name: 'تشاد' },
  { code: 'CL', dial: '56', name: 'تشيلي' },
  { code: 'CN', dial: '86', name: 'الصين' },
  { code: 'CO', dial: '57', name: 'كولومبيا' },
  { code: 'CG', dial: '242', name: 'الكونغو' },
  { code: 'CD', dial: '243', name: 'الكونغو الديمقراطية' },
  { code: 'CR', dial: '506', name: 'كوستاريكا' },
  { code: 'CI', dial: '225', name: 'ساحل العاج' },
  { code: 'HR', dial: '385', name: 'كرواتيا' },
  { code: 'CU', dial: '53', name: 'كوبا' },
  { code: 'CY', dial: '357', name: 'قبرص' },
  { code: 'CZ', dial: '420', name: 'التشيك' },
  { code: 'DK', dial: '45', name: 'الدنمارك' },
  { code: 'DM', dial: '1767', name: 'دومينيكا' },
  { code: 'DO', dial: '1809', name: 'الدومينيكان' },
  { code: 'EC', dial: '593', name: 'الإكوادور' },
  { code: 'SV', dial: '503', name: 'السلفادور' },
  { code: 'GQ', dial: '240', name: 'غينيا الاستوائية' },
  { code: 'ER', dial: '291', name: 'إريتريا' },
  { code: 'EE', dial: '372', name: 'إستونيا' },
  { code: 'SZ', dial: '268', name: 'إسواتيني' },
  { code: 'ET', dial: '251', name: 'إثيوبيا' },
  { code: 'FJ', dial: '679', name: 'فيجي' },
  { code: 'FI', dial: '358', name: 'فنلندا' },
  { code: 'FR', dial: '33', name: 'فرنسا' },
  { code: 'GA', dial: '241', name: 'الغابون' },
  { code: 'GM', dial: '220', name: 'غامبيا' },
  { code: 'GE', dial: '995', name: 'جورجيا' },
  { code: 'GH', dial: '233', name: 'غانا' },
  { code: 'GI', dial: '350', name: 'جبل طارق' },
  { code: 'GR', dial: '30', name: 'اليونان' },
  { code: 'GL', dial: '299', name: 'غرينلاند' },
  { code: 'GD', dial: '1473', name: 'غرينادا' },
  { code: 'GT', dial: '502', name: 'غواتيمالا' },
  { code: 'GN', dial: '224', name: 'غينيا' },
  { code: 'GW', dial: '245', name: 'غينيا بيساو' },
  { code: 'GY', dial: '592', name: 'غيانا' },
  { code: 'HT', dial: '509', name: 'هايتي' },
  { code: 'HN', dial: '504', name: 'هندوراس' },
  { code: 'HK', dial: '852', name: 'هونغ كونغ' },
  { code: 'HU', dial: '36', name: 'المجر' },
  { code: 'IS', dial: '354', name: 'آيسلندا' },
  { code: 'IN', dial: '91', name: 'الهند' },
  { code: 'ID', dial: '62', name: 'إندونيسيا' },
  { code: 'IR', dial: '98', name: 'إيران' },
  { code: 'IE', dial: '353', name: 'أيرلندا' },
  { code: 'IT', dial: '39', name: 'إيطاليا' },
  { code: 'JM', dial: '1876', name: 'جامايكا' },
  { code: 'JP', dial: '81', name: 'اليابان' },
  { code: 'KZ', dial: '7', name: 'كازاخستان' },
  { code: 'KE', dial: '254', name: 'كينيا' },
  { code: 'KI', dial: '686', name: 'كيريباتي' },
  { code: 'XK', dial: '383', name: 'كوسوفو' },
  { code: 'KG', dial: '996', name: 'قيرغيزستان' },
  { code: 'LA', dial: '856', name: 'لاوس' },
  { code: 'LV', dial: '371', name: 'لاتفيا' },
  { code: 'LS', dial: '266', name: 'ليسوتو' },
  { code: 'LR', dial: '231', name: 'ليبيريا' },
  { code: 'LI', dial: '423', name: 'ليختنشتاين' },
  { code: 'LT', dial: '370', name: 'ليتوانيا' },
  { code: 'LU', dial: '352', name: 'لوكسمبورغ' },
  { code: 'MO', dial: '853', name: 'ماكاو' },
  { code: 'MG', dial: '261', name: 'مدغشقر' },
  { code: 'MW', dial: '265', name: 'مالاوي' },
  { code: 'MY', dial: '60', name: 'ماليزيا' },
  { code: 'MV', dial: '960', name: 'المالديف' },
  { code: 'ML', dial: '223', name: 'مالي' },
  { code: 'MT', dial: '356', name: 'مالطا' },
  { code: 'MH', dial: '692', name: 'جزر مارشال' },
  { code: 'MU', dial: '230', name: 'موريشيوس' },
  { code: 'MX', dial: '52', name: 'المكسيك' },
  { code: 'FM', dial: '691', name: 'ميكرونيزيا' },
  { code: 'MD', dial: '373', name: 'مولدوفا' },
  { code: 'MC', dial: '377', name: 'موناكو' },
  { code: 'MN', dial: '976', name: 'منغوليا' },
  { code: 'ME', dial: '382', name: 'الجبل الأسود' },
  { code: 'MZ', dial: '258', name: 'موزمبيق' },
  { code: 'MM', dial: '95', name: 'ميانمار' },
  { code: 'NA', dial: '264', name: 'ناميبيا' },
  { code: 'NR', dial: '674', name: 'ناورو' },
  { code: 'NP', dial: '977', name: 'نيبال' },
  { code: 'NL', dial: '31', name: 'هولندا' },
  { code: 'NZ', dial: '64', name: 'نيوزيلندا' },
  { code: 'NI', dial: '505', name: 'نيكاراغوا' },
  { code: 'NE', dial: '227', name: 'النيجر' },
  { code: 'NG', dial: '234', name: 'نيجيريا' },
  { code: 'KP', dial: '850', name: 'كوريا الشمالية' },
  { code: 'MK', dial: '389', name: 'مقدونيا الشمالية' },
  { code: 'NO', dial: '47', name: 'النرويج' },
  { code: 'PK', dial: '92', name: 'باكستان' },
  { code: 'PW', dial: '680', name: 'بالاو' },
  { code: 'PA', dial: '507', name: 'بنما' },
  { code: 'PG', dial: '675', name: 'بابوا غينيا الجديدة' },
  { code: 'PY', dial: '595', name: 'باراغواي' },
  { code: 'PE', dial: '51', name: 'بيرو' },
  { code: 'PH', dial: '63', name: 'الفلبين' },
  { code: 'PL', dial: '48', name: 'بولندا' },
  { code: 'PT', dial: '351', name: 'البرتغال' },
  { code: 'PR', dial: '1787', name: 'بورتوريكو' },
  { code: 'RO', dial: '40', name: 'رومانيا' },
  { code: 'RU', dial: '7', name: 'روسيا' },
  { code: 'RW', dial: '250', name: 'رواندا' },
  { code: 'KN', dial: '1869', name: 'سانت كيتس ونيفيس' },
  { code: 'LC', dial: '1758', name: 'سانت لوسيا' },
  { code: 'VC', dial: '1784', name: 'سانت فنسنت' },
  { code: 'WS', dial: '685', name: 'ساموا' },
  { code: 'SM', dial: '378', name: 'سان مارينو' },
  { code: 'ST', dial: '239', name: 'ساو تومي وبرينسيب' },
  { code: 'SN', dial: '221', name: 'السنغال' },
  { code: 'RS', dial: '381', name: 'صربيا' },
  { code: 'SC', dial: '248', name: 'سيشل' },
  { code: 'SL', dial: '232', name: 'سيراليون' },
  { code: 'SG', dial: '65', name: 'سنغافورة' },
  { code: 'SK', dial: '421', name: 'سلوفاكيا' },
  { code: 'SI', dial: '386', name: 'سلوفينيا' },
  { code: 'SB', dial: '677', name: 'جزر سليمان' },
  { code: 'ZA', dial: '27', name: 'جنوب أفريقيا' },
  { code: 'KR', dial: '82', name: 'كوريا الجنوبية' },
  { code: 'SS', dial: '211', name: 'جنوب السودان' },
  { code: 'ES', dial: '34', name: 'إسبانيا' },
  { code: 'LK', dial: '94', name: 'سريلانكا' },
  { code: 'SR', dial: '597', name: 'سورينام' },
  { code: 'SE', dial: '46', name: 'السويد' },
  { code: 'CH', dial: '41', name: 'سويسرا' },
  { code: 'TW', dial: '886', name: 'تايوان' },
  { code: 'TJ', dial: '992', name: 'طاجيكستان' },
  { code: 'TZ', dial: '255', name: 'تنزانيا' },
  { code: 'TH', dial: '66', name: 'تايلاند' },
  { code: 'TL', dial: '670', name: 'تيمور الشرقية' },
  { code: 'TG', dial: '228', name: 'توغو' },
  { code: 'TO', dial: '676', name: 'تونغا' },
  { code: 'TT', dial: '1868', name: 'ترينيداد وتوباغو' },
  { code: 'TR', dial: '90', name: 'تركيا' },
  { code: 'TM', dial: '993', name: 'تركمانستان' },
  { code: 'TV', dial: '688', name: 'توفالو' },
  { code: 'UG', dial: '256', name: 'أوغندا' },
  { code: 'UA', dial: '380', name: 'أوكرانيا' },
  { code: 'GB', dial: '44', name: 'المملكة المتحدة' },
  { code: 'US', dial: '1', name: 'الولايات المتحدة' },
  { code: 'UY', dial: '598', name: 'الأوروغواي' },
  { code: 'UZ', dial: '998', name: 'أوزبكستان' },
  { code: 'VU', dial: '678', name: 'فانواتو' },
  { code: 'VA', dial: '379', name: 'الفاتيكان' },
  { code: 'VE', dial: '58', name: 'فنزويلا' },
  { code: 'VN', dial: '84', name: 'فيتنام' },
  { code: 'ZM', dial: '260', name: 'زامبيا' },
  { code: 'ZW', dial: '263', name: 'زيمبابوي' },
]

export const COUNTRIES: Country[] = [...PRIORITY, ...REST]

/** يعيد بيانات الدولة حسب رمز ISO (أو السعودية افتراضياً). */
export function countryByCode(code: string): Country {
  return COUNTRIES.find(c => c.code === code) ?? COUNTRIES[0]
}