/** Shared First1Saudi rules for every image-generation entry point. */
export const STUDIO_BRAND_RULES = `FIRST1SAUDI — SHARED DESIGN RULES
Priority: verified source facts and exact user-approved copy; reference identity and original digital logos; these brand rules; selected direction; optional photographic template. A historical direction or template must never override these rules.
Brand: deep emerald green #0A3A2A and luxurious gold #D4AF37 with rich gradients; white only for names and small supporting text. Premium, celebratory Saudi aesthetic, cinematic spotlights and golden glow. Thin elegant curved gold dividers and subtle Islamic geometric background texture. Full-bleed artwork, never a white logo panel or empty logo frame.
Reference photos: use all supplied photos and preserve exact faces, expressions, skin tone, clothing, body proportions and original poses. Never beautify, redraw or invent a person. Adapt the surrounding layout to the photographs. With no reference photo, use a professional symbolic illustration of the field, NEVER a fake human face.
Background: relate it to the actual topic (arena for sports, laboratory for science, digital environment for technology, relevant venue for culture). Grade only the surrounding background into emerald and gold; keep it atmospheric and subordinate to the hero. Event branding may be non-readable atmosphere only.
Typography: GE Dinar One Heavy, or Lomar/Din Next Arabic Heavy; crisp connected RTL Arabic, short correctly spelled copy, full verified names exactly once. No invented facts, ranks, dates, institutions or numbers. Internal analysis, image descriptions and design instructions must never appear as visible text. English is allowed only as one small event-subtitle translation line when supplied.
DIGITAL ASSETS ONLY: NEVER generate brand/event logos, social-media icons, handles (@...), URLs or watermarks. Small topic/fact icons are allowed; they are not social-media icons.
Reserve bottom-center clean space for later digital social handles; leave it empty during AI generation. Reserve the lower-right logo pocket AND the area below it through the bottom edge with NO text, labels, captions, names, numbers, icons, people or video. The original logo is composited digitally after generation; never add a slogan or any words underneath it. Continue the same subtle emerald background texture behind these pockets, with no box, border or separate panel.
QUALITY CHECK before output: exact reference likeness and poses; correct full names and Arabic spelling; factual topical background; emerald/gold identity; empty digital-asset pockets; no AI logos/social icons/handles/URLs, garbled text or distorted elements. If reliable Arabic rendering is impossible, leave the affected text areas empty rather than inventing or garbling lettering; use the quoted copy and named placement instructions as the handoff for digital typesetting.`

export const STUDIO_LOGO_RESERVATION = 'On the 1080×1350 canvas keep the last 180 pixels at the right and last 220 pixels at the bottom free of foreground content, including the space underneath the digitally overlaid logo. Keep bottom-center free for a separate digital social-handle overlay.'

export const STUDIO_NEWS_LAYOUT_RULES = `NEWS WORKFLOW AND LAYOUT
First classify: competition win / patent-innovation / historic first / appointment / award-honor / scientific discovery / other. Use only documented distinctions: never claim a historic first without evidence.
Headline formulas: competition → rank or medal; patent → براءة اختراع + field; historic first → أول سعودي/سعودية + feat; appointment → position + verified distinction; award → award name; discovery → discovery type; other → a factual concise achievement. Headline is 2–5 Arabic words; move details into the subtitle. A golden medal/number badge is allowed ONLY for competitions or explicitly ranked achievements, never for patents, appointments or historic firsts/records.
Top to bottom: centered dark-green plaque with thin gold border and exact gold Arabic text "إنجاز سعودي"; prominent reference-photo hero(s); huge luxurious gold 3D achievement headline; short gold Arabic event subtitle and at most one smaller supplied English translation; rounded gold-outline names box with full verified names in white; four small circular gold topic icons with 1–3-word Arabic fact labels; clean digital-asset space at bottom.
Choose four story-specific verified facts: competition (medal, sport, event/year, distinction); patent (field, office/year, institution, impact); historic first (feat, field, year, distinction); appointment (position, institution, field, distinction); award (award, body, year, field); discovery (type, field, institution/year, impact). If fewer than four facts are documented, show fewer; never fill gaps by inventing facts.
Adapt the three directions to this news: Classic Celebration (الاحتفالي الكلاسيكي), balanced formal established structure; Dramatic (الدرامي الحماسي), stronger lighting and hero presence with sporting energy, scientific breakthrough or historic gravitas as appropriate; Minimal Premium (الأنيق المختصر), restrained luxury, fewer effects and more negative space. Keep the same information hierarchy and identity in all three.
Exceptions: greetings use only approved greeting copy, without the achievement plaque or invented news facts; multi-person infographics preserve the supplied image/name pairing and card order; educational content and event coverage keep their appropriate information structure. Explicit video windows override hero/layout placement while staying clear of digital-asset pockets. Exceptions never override brand, reference identity, factuality or digital-logo rules.`

export const STUDIO_DESIGN_DIRECTIONS = [
  { title: 'الاحتفالي الكلاسيكي', mood: 'فخر سعودي وفخامة متوازنة', brief: 'التكوين المعتمد المتوازن: لوحة إنجاز سعودي، الصورة الحقيقية، عنوان ذهبي مختصر، العنوان الفرعي، صندوق الأسماء الكاملة وصف حقائق الخبر الموثقة؛ الخلفية مناسبة للمجال.' },
  { title: 'الدرامي الحماسي', mood: 'إضاءة سينمائية وحضور قوي', brief: 'التسلسل نفسه مع حضور أكبر للصورة وإضاءة ذهبية درامية؛ طاقة منافسة للرياضة، إحساس بالاكتشاف للعلوم والاختراع، وهيبة للسوابق التاريخية، دون تغيير الوجه أو الوضعية.' },
  { title: 'الأنيق المختصر', mood: 'وقار وفخامة هادئة', brief: 'التسلسل نفسه بمساحات سالبة أوسع وزخارف وتأثيرات أقل وتايبوغرافي راقٍ؛ اختصار الحقائق دون اختلاقها وحماية مساحة الشعار والتذييل الرقمي.' },
]
