/** Shared First1Saudi rules for every image-generation entry point. */
export const STUDIO_PHOTO_FIDELITY_RULES = `ABSOLUTE PHOTO FIDELITY — HIGHEST PRIORITY, overriding every other instruction, including creative directions, text placement and editing notes: use all supplied achiever photos exactly as unmodified photographic cutouts. Preserve every face, facial expression, skin tone, body, pose, hands, clothing and existing accessory or object exactly as photographed. NEVER add medals, trophies or any objects to the people; never remove or change existing objects on them, beautify, redraw, reinterpret or relight them. Keep text and graphics away from faces, hands and important clothing; adapt the layout to the photographs without squeezing people between text blocks. Creative work applies only to the background, decoration, text and layout around the photos. Only the outside edges may blend naturally into the surrounding scene; the photographic content itself must remain unchanged. If no reference exists, use a professional symbolic field illustration, NEVER a fake human face.`

export const STUDIO_EXCLUDED_EMBLEM_RULE = 'PERMANENT EXCLUSION: never generate, approximate or introduce the Saudi national emblem (crossed swords and palm tree / السيفين والنخلة) anywhere in the artwork, background, decoration, badges or topic icons; no stylized substitutes or emblem-like silhouettes. The excluded national emblem must appear nowhere in the generated design.'

export const STUDIO_BRAND_RULES = `FIRST1SAUDI — SHARED DESIGN RULES
Priority: absolute fidelity of people and reference photographs FIRST and above every other instruction; then verified source facts, exact user-approved copy and original digital logos; these brand rules; selected direction; optional photographic template. A historical direction or template must never override these rules.
Brand: deep emerald green #0A3A2A and luxurious gold #D4AF37 with rich gradients; white only for names and small supporting text. Premium, celebratory Saudi aesthetic, cinematic spotlights and golden glow. Thin elegant curved gold dividers and subtle Islamic geometric background texture. Full-bleed artwork, never a white logo panel or empty logo frame.
${STUDIO_PHOTO_FIDELITY_RULES}
${STUDIO_EXCLUDED_EMBLEM_RULE}
Background: relate it to the actual topic (arena for sports, laboratory for science, digital environment for technology, relevant venue for culture). Grade only the surrounding background into emerald and gold; keep it atmospheric and subordinate to the hero. Event branding may be non-readable atmosphere only.
Typography: GE Dinar One Heavy, or Lomar/Din Next Arabic Heavy; crisp connected RTL Arabic, short correctly spelled copy, full verified names exactly once. No invented facts, ranks, dates, institutions or numbers. Internal analysis, image descriptions and design instructions must never appear as visible text. English is allowed only as one small event-subtitle translation line when supplied.
DIGITAL ASSETS ONLY: NEVER generate brand/event logos, social-media icons, handles (@...), URLs or watermarks. Small topic/fact icons are allowed; they are not social-media icons.
The FINAL OUTPUT MUST include a full-width curved emerald footer with a gold-edged swoosh above it, all five white social icons (X, Instagram, LinkedIn, Facebook, TikTok), and the exact handle @First1Saudi. These are composed digitally after generation, never drawn by AI. Reserve the bottom 170 pixels for that digital footer, with social icons and handle to the left/center and the original logo directly on the same full-width footer at the lower right. Leave these elements empty during AI generation. Reserve the lower-right logo pocket AND the area below it through the bottom edge with NO text, labels, captions, names, numbers, icons, people or video. The original logo is composited digitally after generation; never add a slogan or any words underneath it. Keep the underlying generated artwork continuous across the entire width. NEVER draw a reserved-space rectangle, rounded card, square, frame, border, solid-color block, white background, or separate panel behind the logo, even if it uses the same green palette. Do not visually outline or distinguish the reserved logo pocket. No AI decoration in the reserved pockets; the curve and footer are added digitally across the full width, not as a logo enclosure.
QUALITY CHECK before delivery — every item must pass: exact reference faces, expressions, clothing and poses with nothing added to or changed on people; headline formula matches the classified news type; correct full names and Arabic spelling; factual topical background; emerald/gold identity; AI base leaves undecorated digital-asset pockets, and final digital composition contains the curve, five social icons, exact @First1Saudi and original logo without any separate logo frame; excluded national emblem nowhere; no AI logos/social icons/handles/URLs, garbled text or distorted elements. If reliable Arabic rendering is impossible, generate the entire design WITHOUT text rather than inventing or garbling lettering. Clearly identify every exact text and its named placement in the saved prompt/copy map for digital typesetting; never print the failure warning or placement instructions on the artwork.`

export const STUDIO_LOGO_RESERVATION = 'On the 1080×1350 canvas keep the last 180 pixels at the right and last 220 pixels at the bottom free of foreground content, including the space underneath the digitally overlaid logo. Keep bottom-center free for a separate digital social-handle overlay. Do not draw either pocket as a visible box or card; continue the surrounding background seamlessly. The full-width curved footer, five social icons and @First1Saudi are composited digitally into the final image, with no separate frame behind the logo.'

export const STUDIO_NEWS_LAYOUT_RULES = `NEWS WORKFLOW AND LAYOUT
Mandatory order for each story: understand and classify the news FIRST; select its headline and facts; interpret and generate the three directions through that news type; run the quality checklist before delivery. Do not generate a design before its news type is clear. Classify: competition win / patent-innovation / historic first / appointment / award-honor / scientific discovery / other. Use only documented distinctions: never claim a historic first without evidence.
Headline formulas: competition → rank or medal; patent → براءة اختراع + field; historic first → أول سعودي/سعودية + feat; appointment → position + verified distinction; award → award name; discovery → discovery type; other → a factual concise achievement. Headline is 2–5 Arabic words; move details into the subtitle. A separate graphic golden medal/number badge, outside the reference photos and never attached to a person, is allowed ONLY for competitions or explicitly ranked achievements, never for patents, appointments or historic firsts/records.
Top to bottom: a centered short gold Arabic header_label tailored to this particular story, such as a verified event name, award context, innovation theme or historic distinction; vary the wording naturally with the story, never default every poster to "إنجاز سعودي"; an optional thin gold-bordered plaque may hold this story-specific label; real achievers from unmodified reference-photo cutouts side by side in the center as the visual heart; every other element supports them and never competes with them; huge luxurious gold 3D achievement headline; short gold Arabic event subtitle with one smaller supplied English translation directly beneath it when available; rounded gold-outline names box with full verified names in white; four small circular gold topic icons with 1–3-word Arabic fact labels; clean digital-asset space at bottom.
Arabic news copy appears ONLY in the header plaque, achievement headline, subtitle, full-names box and info labels; English ONLY in the single smaller event-subtitle translation. Choose four story-specific verified facts: competition (medal, sport, event/year, distinction); patent (field, office/year, institution, impact); historic first (feat, field, year, distinction); appointment (position, institution, field, distinction); award (award, body, year, field); discovery (type, field, institution/year, impact). If fewer than four facts are documented, show fewer; never fill gaps by inventing facts.
Adapt the three directions to this news: Classic Celebration (الاحتفالي الكلاسيكي), balanced formal established structure; Dramatic (الدرامي الحماسي), stronger lighting and hero presence with sporting energy, scientific breakthrough or historic gravitas as appropriate; Minimal Premium (الأنيق المختصر), restrained luxury, fewer effects and more negative space. Keep the same information hierarchy and identity in all three.
Exceptions: greetings use only approved greeting copy, without the achievement plaque or invented news facts; multi-person infographics preserve the supplied image/name pairing and card order; educational content and event coverage keep their appropriate information structure. Explicit video windows override hero/layout placement while staying clear of digital-asset pockets. Exceptions never override brand, reference identity, factuality or digital-logo rules.`

export const STUDIO_DESIGN_DIRECTIONS = [
  { title: 'الاحتفالي الكلاسيكي', mood: 'فخر سعودي وفخامة متوازنة', brief: 'التكوين المعتمد المتوازن: عبارة علوية قصيرة مستوحاة من هذا الخبر، الصورة الحقيقية، عنوان ذهبي مختصر، العنوان الفرعي، صندوق الأسماء الكاملة وصف حقائق الخبر الموثقة؛ الخلفية مناسبة للمجال.' },
  { title: 'الدرامي الحماسي', mood: 'إضاءة سينمائية وحضور قوي', brief: 'التسلسل نفسه مع حضور أكبر للصورة وإضاءة ذهبية درامية؛ طاقة منافسة للرياضة، إحساس بالاكتشاف للعلوم والاختراع، وهيبة للسوابق التاريخية، دون تغيير الوجه أو الوضعية.' },
  { title: 'الأنيق المختصر', mood: 'وقار وفخامة هادئة', brief: 'التسلسل نفسه بمساحات سالبة أوسع وزخارف وتأثيرات أقل وتايبوغرافي راقٍ؛ اختصار الحقائق دون اختلاقها وحماية مساحة الشعار والتذييل الرقمي.' },
]
