/** Shared First1Saudi rules for every image-generation entry point. */
export const STUDIO_NO_SOURCE_IMAGE_RULES = 'NO SOURCE PHOTO: if no source photo is supplied, create a typography-led design using verified text, small topic/fact icons, abstract geometric decoration and the required branded footer ONLY. NEVER a fake human face; no invented person, portrait, silhouette, stock photo, realistic scene, venue, laboratory, landscape, product, invention or illustrative replacement hero. Do not infer an image from a name, news text, old concept, template or editing note. This rule overrides all photographic or scenic creative directions when there is no source photo.'

export const STUDIO_PHOTO_FIDELITY_RULES = `ABSOLUTE PHOTO FIDELITY — HIGHEST PRIORITY, overriding every other instruction, including creative directions, text placement and editing notes: use all supplied achiever photos exactly as unmodified photographic cutouts. Preserve every face, facial expression, skin tone, body, pose, hands, clothing and existing accessory or object exactly as photographed. NEVER add medals, trophies or any objects to the people; never remove or change existing objects on them, beautify, redraw, reinterpret or relight them. Keep text and graphics away from faces, hands and important clothing; adapt the layout to the photographs without squeezing people between text blocks. Creative work applies only to the background, decoration, text and layout around the photos. Only the outside edges may blend naturally into the surrounding scene; the photographic content itself must remain unchanged. ${STUDIO_NO_SOURCE_IMAGE_RULES}`

export const STUDIO_EXCLUDED_EMBLEM_RULE = 'PERMANENT EXCLUSION: never generate, approximate or introduce the Saudi national emblem (crossed swords and palm tree / السيفين والنخلة) anywhere in the artwork, background, decoration, badges or topic icons; no stylized substitutes or emblem-like silhouettes. The excluded national emblem must appear nowhere in the generated design.'

export const STUDIO_BRAND_RULES = `FIRST1SAUDI — SHARED DESIGN RULES
Priority: absolute fidelity of people and reference photographs FIRST and above every other instruction; then verified source facts, exact user-approved copy and original digital logos; these brand rules; selected direction; optional photographic template. A historical direction or template must never override these rules.
Brand: deep emerald green #0A3A2A and luxurious gold #D4AF37 with rich gradients; ivory #F8F5EC, warm white and pale emerald are allowed as dominant backgrounds for lighter directions. Emerald and gold remain the identifying accents; a dark background is NOT mandatory. Premium, celebratory Saudi aesthetic, lighting tailored to the direction: balanced warm light for Classic, cinematic spotlights for Dramatic, and soft daylight for Minimal; golden accents remain restrained and appropriate. Thin elegant curved gold dividers and subtle Islamic geometric background texture. Full-bleed artwork, never a white logo panel or empty logo frame.
${STUDIO_PHOTO_FIDELITY_RULES}
${STUDIO_EXCLUDED_EMBLEM_RULE}
Background: relate it to the actual topic (arena for sports, laboratory for science, digital environment for technology, relevant venue for culture). Use emerald/gold either as the background palette or as accents over a light ivory, warm-white or pale-emerald scene according to the selected direction; never darken every direction by default; keep it atmospheric and subordinate to the hero. Event branding may be non-readable atmosphere only.
Typography: GE Dinar One Heavy, or Lomar/Din Next Arabic Heavy; crisp connected RTL Arabic, short correctly spelled copy, full verified names exactly once. No invented facts, ranks, dates, institutions or numbers. Internal analysis, image descriptions and design instructions must never appear as visible text. English is allowed only as one small event-subtitle translation line when supplied, plus the mandatory exact footer account "@First1Saudi".
DIGITAL LOGOS ONLY: NEVER generate brand/event logos, URLs or watermarks. ONLY original logos are composited digitally after generation. The AI MUST generate the social icons, exact account handle and curved footer in the design itself. Small topic/fact icons are allowed.
MANDATORY GENERATED FOOTER: draw a full-width curved deep emerald footer with an elegant green swoosh and thin gold curved divider above it. At its left/center render ALL FIVE recognizable white social icons in this order: X, Instagram, LinkedIn, Facebook, TikTok; equal size, balanced spacing and all fully visible. Beside them render the exact bold white account text "@First1Saudi". Never omit any icon, the handle or the curve. These elements are part of AI image generation, not a later programmatic overlay. Keep them away from the lower-right logo area and never put text underneath the logo.
Reserve the lower-right logo area AND the area below it through the bottom edge with NO text, labels, captions, names, numbers, social icons, people or video. The original logo alone is composited digitally after generation; never add a slogan or any words underneath it. Continue the SAME full-width curved footer behind the logo, with NO separate rectangle, rounded card, square, frame, border, solid-color block, white background or individual panel behind it, even if it uses the same green palette. Never visibly outline or distinguish the reserved logo area.
QUALITY CHECK before delivery — every item must pass: exact reference faces, expressions, clothing and poses with nothing added to or changed on people; headline formula matches the classified news type; correct full names and Arabic spelling; factual topical background; emerald/gold identity; generated design contains the curve, all five social icons and exact @First1Saudi; original logo is digitally placed on the same footer without any separate logo frame; excluded national emblem nowhere; no AI-generated logos or URLs, garbled text or distorted elements. If reliable Arabic rendering is impossible, generate the design WITHOUT Arabic story text rather than inventing or garbling lettering; retain the mandatory social icons, curve and Latin handle "@First1Saudi". Clearly identify every exact text and its named placement in the saved prompt/copy map for digital typesetting; never print the failure warning or placement instructions on the artwork.`

export const STUDIO_LOGO_RESERVATION = 'On the 1080×1350 canvas keep the last 180 pixels at the right and last 220 pixels at the bottom free of text and foreground content for the original digital logo, including the space underneath it. Do not draw this area as a visible box or card; continue the same full-width curved footer behind it seamlessly. Generate the curve, five social icons and exact "@First1Saudi" on the footer left/center; only the logo is added digitally.'

export const STUDIO_NEWS_LAYOUT_RULES = `NEWS WORKFLOW AND LAYOUT
Mandatory order for each story: understand and classify the news FIRST; select its headline and facts; interpret and generate the three directions through that news type; run the quality checklist before delivery. Do not generate a design before its news type is clear. Classify: competition win / patent-innovation / historic first / appointment / award-honor / scientific discovery / other. Use only documented distinctions: never claim a historic first without evidence.
NAME-FIRST READING ORDER — the full verified achiever name is the primary headline, the largest and most prominent text near the top. Render the name in white on dark backgrounds or deep emerald on light surfaces for clear contrast. Immediately BELOW the name, with no photograph, badge or unrelated line interrupting them, place a concise Arabic achievement sentence that grammatically completes the name as one continuous thought: the verified full name then an action clause such as تحصل على الدكتوراه بتقدير ممتاز مرتفع (ONLY when those facts are verified). Match the verb, gender, number and tense to the actual story; never mechanically use تحصل على for every achievement. For wins use a factual winning clause, for patents a patent/innovation clause, for appointments a position clause, and for discoveries the verified discovery action. Do not replace the name with a generic slogan such as "ريادة حضرية سعودية", a medal rank or award category. Do not demote the name into a small box after a large slogan or event paragraph. Do not repeat the name in the achievement sentence. GLOBAL FACT UNIQUENESS: each factual detail appears ONCE across the achievement sentence, context/subtitle, optional tag and icon phrases. Different wording does not make a repeated fact new. Allocate the core achievement to the name continuation and only additional distinct details to the icons; omit redundant blocks or icons rather than padding them. Repeated connecting words are acceptable; repeating information is not.
Visual journey: prominent full name → immediately connected achievement sentence → brief additional factual context/event subtitle if needed → story-specific icon facts → mandatory curved social footer. The unchanged reference photo(s) remain visually prominent alongside or around this text sequence, but never interrupt the name/sentence pair. An optional story-specific tag is secondary and must not compete with or replace the name. Use a smaller supplied English event translation only if available. When no verified person name exists (event/educational content), use the factual topic title rather than inventing a name. Greetings retain their approved copy.
INFO ROW: up to four small circular gold topic icons, EACH with a concise meaningful Arabic PHRASE below it (usually 3–7 words; clarity matters more than a rigid word count). Each phrase must communicate an actual detail of THIS achievement, not merely label a field, place or institution. INTERNAL grammar examples only — never print these unless they match verified source facts. For a verified doctorate story: "حصلت على الدكتوراه من جامعة القصيم", "بتقدير ممتاز مرتفع", "بحث في إعادة تأهيل الأحياء", "دراسة تطبيقية على ينبع البحر" only if supported by the source. Never reduce them to bare labels such as "جامعة القصيم", "إعادة التأهيل" or "ينبع البحر". Keep gender/tense consistent and avoid repeating the same fact across icon captions OR any main sentence, tag or subtitle, even when paraphrased. Choose distinct supported facts for the news type; if fewer than four are documented, show fewer and never fill gaps by inventing facts. Legacy one-word labels must be rewritten into meaningful phrases using ONLY the verified achievement/context; omit any label whose relationship cannot be established.
A separate golden medal/number badge, outside the reference photos and never attached to a person, is allowed ONLY for competitions or explicitly ranked achievements, never for patents, appointments or historic firsts/records. It must stay secondary to the name. Arabic copy is limited to the primary name, connected achievement sentence, optional secondary story tag/event context and icon phrases. The mandatory footer handle "@First1Saudi" is the only additional account text. English is limited to one smaller event translation and the mandatory footer account.
BACKGROUND VARIETY IS MANDATORY ACROSS THE THREE DIRECTIONS. Classic Celebration (الاحتفالي الكلاسيكي): a balanced medium-tone emerald or pale-emerald topical background with warm gold accents, formal established structure and balanced lighting. Dramatic (الدرامي الحماسي): deep dark emerald background, cinematic surrounding light and stronger hero presence with sporting energy, scientific breakthrough or historic gravitas as appropriate. Minimal Premium (الأنيق المختصر): a clearly LIGHT ivory, warm-white or very pale-emerald dominant background, emerald typography, refined gold accents, soft light, fewer effects and more negative space. Do not output all three on dark backgrounds; their background brightness and lighting must differ visibly. Adjust gold depth and text color for readability without changing the real photos. Keep the same name-first reading order and connected achievement sentence in all three; vary styling, not the logical reading order.
Exceptions: greetings use only approved greeting copy PLUS the mandatory generated social footer, without the achievement plaque or invented news facts; multi-person infographics preserve the supplied image/name pairing and card order; educational content and event coverage keep their appropriate information structure. Explicit video windows override hero/layout placement while staying clear of digital-asset pockets. Exceptions never override brand, reference identity, factuality or digital-logo rules.`

export const STUDIO_DESIGN_DIRECTIONS = [
  { title: 'الاحتفالي الكلاسيكي', mood: 'فخر سعودي وفخامة متوازنة', brief: 'التكوين المتوازن: الصورة الحقيقية حول كتلة الاسم والإنجاز دون قطع تسلسل قراءتها، الاسم الكامل أكبر نص، تحته مباشرة عبارة فعلية تكمل سياق الإنجاز، ثم تفاصيل موثقة وعبارات مفيدة تحت الأيقونات؛ خلفية مرتبطة بالمجال بزمردي متوسط أو أخضر فاتح وإضاءة دافئة متوازنة، مختلفة بوضوح عن الخلفية الدرامية الداكنة.' },
  { title: 'الدرامي الحماسي', mood: 'إضاءة سينمائية وحضور قوي', brief: 'التسلسل نفسه مع خلفية زمردية داكنة وحضور أكبر للصورة وإضاءة ذهبية سينمائية حولها؛ طاقة منافسة للرياضة، إحساس بالاكتشاف للعلوم والاختراع، وهيبة للسوابق التاريخية، دون تغيير الوجه أو الوضعية.' },
  { title: 'الأنيق المختصر', mood: 'وقار وفخامة هادئة', brief: 'التسلسل نفسه بخلفية فاتحة سائدة (عاجي أو أبيض دافئ أو زمردي باهت جداً) ونصوص زمردية ولمسات ذهبية وإضاءة ناعمة؛ بمساحات سالبة أوسع وزخارف وتأثيرات أقل وتايبوغرافي راقٍ؛ اختصار الحقائق دون اختلاقها وحماية مساحة الشعار والتذييل الرقمي.' },
]
