CREATE TABLE public.membership_topups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  topup_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  membership_id uuid NOT NULL REFERENCES public.memberships(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  item_type text NOT NULL CHECK (item_type IN ('publication_credit', 'reshare_quote', 'pin', 'paid_campaign')),
  quantity integer NOT NULL CHECK (quantity BETWEEN 1 AND 20),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price > 0),
  unit_budget numeric(12,2) NOT NULL DEFAULT 0 CHECK (unit_budget >= 0),
  subtotal numeric(12,2) NOT NULL CHECK (subtotal > 0),
  vat_amount numeric(12,2) NOT NULL CHECK (vat_amount >= 0),
  total_amount numeric(12,2) NOT NULL CHECK (total_amount > 0),
  status text NOT NULL DEFAULT 'pending_payment' CHECK (status IN ('pending_payment', 'paid', 'failed', 'cancelled', 'refunded')),
  payment_provider text CHECK (payment_provider IN ('moyasar', 'tamara', 'bank_transfer')),
  provider_payment_id text,
  provider_response jsonb,
  paid_at timestamptz,
  receipt_sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_membership_topups_provider_payment
  ON public.membership_topups(payment_provider, provider_payment_id)
  WHERE provider_payment_id IS NOT NULL;
CREATE INDEX idx_membership_topups_membership_created
  ON public.membership_topups(membership_id, created_at DESC);

ALTER TABLE public.membership_topups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Members can view own topups"
  ON public.membership_topups FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

GRANT SELECT ON public.membership_topups TO authenticated;

CREATE OR REPLACE FUNCTION public.apply_membership_topup(
  p_topup_id uuid,
  p_provider text,
  p_provider_payment_id text,
  p_provider_response jsonb DEFAULT NULL
) RETURNS public.membership_topups
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_topup public.membership_topups;
  v_membership public.memberships;
  v_credit_wallet public.membership_credit_wallets;
  v_benefit_wallet public.membership_benefit_wallets;
BEGIN
  IF p_provider NOT IN ('moyasar', 'tamara', 'bank_transfer') THEN
    RAISE EXCEPTION 'invalid_topup_provider';
  END IF;

  SELECT * INTO v_topup
  FROM public.membership_topups
  WHERE id = p_topup_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'membership_topup_not_found'; END IF;
  IF v_topup.status = 'paid' THEN RETURN v_topup; END IF;
  IF v_topup.status <> 'pending_payment' THEN RAISE EXCEPTION 'membership_topup_not_payable'; END IF;

  SELECT * INTO v_membership
  FROM public.memberships
  WHERE id = v_topup.membership_id
  FOR UPDATE;
  IF NOT FOUND OR v_membership.status <> 'active' OR now() >= v_membership.ends_at THEN
    RAISE EXCEPTION 'membership_inactive';
  END IF;

  UPDATE public.membership_topups
  SET status = 'paid', payment_provider = p_provider,
      provider_payment_id = p_provider_payment_id,
      provider_response = p_provider_response,
      paid_at = COALESCE(paid_at, now()), updated_at = now()
  WHERE id = v_topup.id
  RETURNING * INTO v_topup;

  IF v_topup.item_type = 'publication_credit' THEN
    SELECT * INTO v_credit_wallet
    FROM public.membership_credit_wallets
    WHERE membership_id = v_topup.membership_id
    FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'membership_wallet_unavailable'; END IF;

    UPDATE public.membership_credit_wallets
    SET total_credits = total_credits + v_topup.quantity, updated_at = now()
    WHERE id = v_credit_wallet.id;

    INSERT INTO public.membership_credit_ledger (
      membership_id, wallet_id, transaction_type, credits, note, idempotency_key
    ) VALUES (
      v_topup.membership_id, v_credit_wallet.id, 'grant', v_topup.quantity,
      'تعزيز رصيد العضوية بعملية شراء إضافية', 'topup:' || v_topup.id::text
    ) ON CONFLICT (idempotency_key) DO NOTHING;
  ELSE
    INSERT INTO public.membership_benefit_wallets (
      membership_id, benefit_type, total_units, unit_budget, expires_at
    ) VALUES (
      v_topup.membership_id, v_topup.item_type, v_topup.quantity,
      v_topup.unit_budget, v_membership.ends_at
    )
    ON CONFLICT (membership_id, benefit_type) DO UPDATE
      SET total_units = public.membership_benefit_wallets.total_units + EXCLUDED.total_units,
          unit_budget = GREATEST(public.membership_benefit_wallets.unit_budget, EXCLUDED.unit_budget),
          updated_at = now()
    RETURNING * INTO v_benefit_wallet;

    INSERT INTO public.membership_benefit_ledger (
      membership_id, wallet_id, transaction_type, units, note, idempotency_key
    ) VALUES (
      v_topup.membership_id, v_benefit_wallet.id, 'grant', v_topup.quantity,
      'تعزيز مزايا العضوية بعملية شراء إضافية', 'topup:' || v_topup.id::text
    ) ON CONFLICT (idempotency_key) DO NOTHING;
  END IF;

  RETURN v_topup;
END; $$;

REVOKE ALL ON FUNCTION public.apply_membership_topup(uuid,text,text,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_membership_topup(uuid,text,text,jsonb) TO service_role;
