create table if not exists public.x_post_metric_snapshots (
  id bigint generated by default as identity primary key,
  x_post_id text not null references public.first1_x_archive_posts(x_post_id) on delete cascade,
  captured_at timestamptz not null default now(),
  post_age_hours integer not null default 0,
  public_metrics jsonb not null default '{}'::jsonb,
  non_public_metrics jsonb not null default '{}'::jsonb,
  organic_metrics jsonb not null default '{}'::jsonb
);

create index if not exists idx_x_metric_snapshots_post_time
  on public.x_post_metric_snapshots (x_post_id, captured_at desc);

create table if not exists public.x_growth_conversations (
  x_post_id text primary key,
  conversation_type text not null check (conversation_type in ('mention', 'reply', 'quote')),
  author_id text,
  author_username text,
  author_name text,
  post_text text not null,
  post_url text not null,
  referenced_post_id text,
  public_metrics jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open', 'reviewed', 'replied', 'dismissed')),
  detected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_x_growth_conversations_status
  on public.x_growth_conversations (status, updated_at desc);

create table if not exists public.x_growth_workspace (
  id boolean primary key default true check (id),
  last_draft_analysis jsonb,
  weekly_plan jsonb,
  settings jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.x_growth_experiments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  hypothesis text not null,
  primary_metric text not null check (primary_metric in ('reply_rate', 'share_rate', 'follow_intent', 'engagement_rate')),
  variant_a jsonb not null,
  variant_b jsonb not null,
  status text not null default 'draft' check (status in ('draft', 'running', 'completed', 'cancelled')),
  result jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_x_growth_experiments_status
  on public.x_growth_experiments (status, created_at desc);

alter table public.x_post_metric_snapshots enable row level security;
alter table public.x_growth_conversations enable row level security;
alter table public.x_growth_workspace enable row level security;
alter table public.x_growth_experiments enable row level security;

revoke all on table public.x_post_metric_snapshots from anon, authenticated;
revoke all on table public.x_growth_conversations from anon, authenticated;
revoke all on table public.x_growth_workspace from anon, authenticated;
revoke all on table public.x_growth_experiments from anon, authenticated;

grant select, insert, update, delete on table public.x_post_metric_snapshots to service_role;
grant select, insert, update, delete on table public.x_growth_conversations to service_role;
grant select, insert, update, delete on table public.x_growth_workspace to service_role;
grant select, insert, update, delete on table public.x_growth_experiments to service_role;
grant usage, select on sequence public.x_post_metric_snapshots_id_seq to service_role;
