-- Fixed-term memberships run alongside direct publish requests.
CREATE TABLE public.membership_plans (
  id text PRIMARY KEY,
  name_ar text NOT NULL,
  description_ar text NOT NULL,
  concurrent_request_limit integer NOT NULL DEFAULT 1 CHECK (concurrent_request_limit > 0),
  revision_rounds integer NOT NULL DEFAULT 1 CHECK (revision_rounds >= 0),
  extra_request_discount_pct numeric(5,2) NOT NULL DEFAULT 0 CHECK (extra_request_discount_pct BETWEEN 0 AND 100),
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  accent text NOT NULL DEFAULT 'silver',
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.membership_plan_prices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id text NOT NULL REFERENCES public.membership_plans(id) ON DELETE CASCADE,
  duration_months integer NOT NULL CHECK (duration_months IN (3, 6, 12)),
  included_credits integer NOT NULL CHECK (included_credits > 0),
  benefit_entitlements jsonb NOT NULL DEFAULT '{}'::jsonb,
  ad_budget_per_30_days numeric(12,2) NOT NULL DEFAULT 0 CHECK (ad_budget_per_30_days >= 0),
  subtotal numeric(12,2) NOT NULL CHECK (subtotal > 0),
  vat_amount numeric(12,2) NOT NULL CHECK (vat_amount >= 0),
  total_amount numeric(12,2) NOT NULL CHECK (total_amount > 0),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (plan_id, duration_months)
);

CREATE TABLE public.memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  membership_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  plan_id text NOT NULL REFERENCES public.membership_plans(id),
  plan_price_id uuid NOT NULL REFERENCES public.membership_plan_prices(id),
  duration_months integer NOT NULL CHECK (duration_months IN (3, 6, 12)),
  status text NOT NULL DEFAULT 'pending_payment' CHECK (status IN (
    'pending_payment', 'payment_review', 'active', 'paused', 'expired', 'cancelled', 'refunded'
  )),
  client_name text NOT NULL,
  client_email text NOT NULL,
  client_phone text,
  subtotal numeric(12,2) NOT NULL,
  vat_amount numeric(12,2) NOT NULL,
  total_amount numeric(12,2) NOT NULL,
  starts_at timestamptz,
  ends_at timestamptz,
  payment_provider text CHECK (payment_provider IN ('moyasar', 'tamara', 'bank_transfer')),
  payment_status text NOT NULL DEFAULT 'pending' CHECK (payment_status IN (
    'pending', 'payment_review', 'paid', 'failed', 'refunded'
  )),
  moyasar_payment_id text,
  tamara_order_id text,
  receipt_url text,
  paid_at timestamptz,
  terms_version text NOT NULL,
  terms_snapshot text NOT NULL,
  terms_accepted_at timestamptz NOT NULL,
  privacy_accepted_at timestamptz NOT NULL,
  acceptance_ip text,
  acceptance_user_agent text,
  contract_path text,
  contract_generated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.membership_credit_wallets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  membership_id uuid NOT NULL UNIQUE REFERENCES public.memberships(id) ON DELETE CASCADE,
  total_credits integer NOT NULL CHECK (total_credits >= 0),
  reserved_credits integer NOT NULL DEFAULT 0 CHECK (reserved_credits >= 0),
  used_credits integer NOT NULL DEFAULT 0 CHECK (used_credits >= 0),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (reserved_credits + used_credits <= total_credits)
);

CREATE TABLE public.membership_benefit_wallets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  membership_id uuid NOT NULL REFERENCES public.memberships(id) ON DELETE CASCADE,
  benefit_type text NOT NULL CHECK (benefit_type IN ('reshare_quote', 'pin', 'paid_campaign')),
  total_units integer NOT NULL CHECK (total_units >= 0),
  reserved_units integer NOT NULL DEFAULT 0 CHECK (reserved_units >= 0),
  used_units integer NOT NULL DEFAULT 0 CHECK (used_units >= 0),
  unit_budget numeric(12,2) NOT NULL DEFAULT 0 CHECK (unit_budget >= 0),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (membership_id, benefit_type),
  CHECK (reserved_units + used_units <= total_units)
);

CREATE TABLE public.membership_credit_ledger (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  membership_id uuid NOT NULL REFERENCES public.memberships(id) ON DELETE CASCADE,
  wallet_id uuid REFERENCES public.membership_credit_wallets(id) ON DELETE SET NULL,
  request_id uuid REFERENCES public.publish_requests(id) ON DELETE SET NULL,
  transaction_type text NOT NULL CHECK (transaction_type IN ('grant', 'reserve', 'consume', 'release', 'adjustment', 'expire')),
  credits integer NOT NULL CHECK (credits <> 0),
  note text,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  idempotency_key text UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.membership_benefit_ledger (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  membership_id uuid NOT NULL REFERENCES public.memberships(id) ON DELETE CASCADE,
  wallet_id uuid REFERENCES public.membership_benefit_wallets(id) ON DELETE SET NULL,
  request_id uuid REFERENCES public.publish_requests(id) ON DELETE SET NULL,
  transaction_type text NOT NULL CHECK (transaction_type IN ('grant', 'reserve', 'consume', 'release', 'adjustment', 'expire')),
  units integer NOT NULL CHECK (units <> 0),
  note text,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  idempotency_key text UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.membership_request_benefits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  membership_id uuid NOT NULL REFERENCES public.memberships(id) ON DELETE CASCADE,
  request_id uuid NOT NULL REFERENCES public.publish_requests(id) ON DELETE CASCADE,
  wallet_id uuid NOT NULL REFERENCES public.membership_benefit_wallets(id) ON DELETE RESTRICT,
  benefit_type text NOT NULL CHECK (benefit_type IN ('reshare_quote', 'pin', 'paid_campaign')),
  units integer NOT NULL DEFAULT 1 CHECK (units > 0),
  status text NOT NULL DEFAULT 'reserved' CHECK (status IN ('reserved', 'consumed', 'released')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (request_id, benefit_type)
);

CREATE TABLE public.membership_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  membership_id uuid NOT NULL REFERENCES public.memberships(id) ON DELETE CASCADE,
  provider text NOT NULL CHECK (provider IN ('moyasar', 'tamara', 'bank_transfer')),
  provider_payment_id text,
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  status text NOT NULL CHECK (status IN ('pending', 'paid', 'failed', 'refunded')),
  provider_response jsonb,
  paid_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_membership_payments_provider_id
  ON public.membership_payments(provider, provider_payment_id)
  WHERE provider_payment_id IS NOT NULL;

CREATE TABLE public.membership_agreements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  membership_id uuid NOT NULL REFERENCES public.memberships(id) ON DELETE CASCADE,
  version text NOT NULL,
  terms_snapshot text NOT NULL,
  accepted_at timestamptz NOT NULL,
  accepted_ip text,
  accepted_user_agent text,
  contract_path text,
  contract_generated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (membership_id, version)
);

ALTER TABLE public.publish_requests
  ADD COLUMN billing_source text NOT NULL DEFAULT 'direct' CHECK (billing_source IN ('direct', 'membership')),
  ADD COLUMN membership_id uuid REFERENCES public.memberships(id) ON DELETE SET NULL,
  ADD COLUMN membership_wallet_id uuid REFERENCES public.membership_credit_wallets(id) ON DELETE SET NULL,
  ADD COLUMN membership_credits integer NOT NULL DEFAULT 0 CHECK (membership_credits >= 0),
  ADD COLUMN membership_credit_status text NOT NULL DEFAULT 'none'
    CHECK (membership_credit_status IN ('none', 'reserved', 'consumed', 'released'));

CREATE INDEX idx_memberships_user_status ON public.memberships(user_id, status, created_at DESC);
CREATE INDEX idx_membership_ledger_membership ON public.membership_credit_ledger(membership_id, created_at DESC);
CREATE INDEX idx_membership_benefit_ledger_membership ON public.membership_benefit_ledger(membership_id, created_at DESC);
CREATE INDEX idx_publish_requests_membership ON public.publish_requests(membership_id, status, created_at DESC);

INSERT INTO public.membership_plans (
  id, name_ar, description_ar, concurrent_request_limit, revision_rounds,
  extra_request_discount_pct, features, accent, sort_order
) VALUES
  ('silver', 'العضوية الفضية', 'رصيد نشر مرن لحضور منتظم طوال مدة العضوية.', 1, 1, 10,
   '["رصيد نشر مرن طوال المدة", "طلب واحد متزامن", "جولة تعديلات", "خصم 10% على الإضافات"]', 'silver', 1),
  ('gold', 'العضوية الذهبية', 'انتشار أوسع مع إعادة النشر أو الاقتباس وتثبيت المنشورات.', 2, 2, 12,
   '["رصيد نشر مرن", "إعادة نشر أو اقتباس", "تثبيت منشورات", "طلبان متزامنان", "خصم 12% على الإضافات"]', 'gold', 2),
  ('platinum', 'العضوية البلاتينية', 'خطة تسويق شخصي وحضور متكامل مع حملات ممولة منظمة.', 3, 3, 15,
   '["خطة تسويق شخصي", "رصيد نشر مرن", "إعادة نشر أو اقتباس", "تثبيت منشورات", "حملة ممولة كل 30 يوماً", "أولوية في التنفيذ"]', 'platinum', 3),
  ('corporate', 'عضوية الشركات', 'إدارة محتوى مؤسسي للقيادات والمنتجات مع مدير حساب وتقارير أداء.', 5, 3, 20,
   '["خطة اتصال مؤسسي", "محتوى القيادات", "محتوى المنتجات", "تقويم شهري", "مدير حساب", "تقرير أداء", "حملتان ممولتان كل 30 يوماً"]', 'corporate', 4);

INSERT INTO public.membership_plan_prices (
  plan_id, duration_months, included_credits, benefit_entitlements, ad_budget_per_30_days,
  subtotal, vat_amount, total_amount
) VALUES
  ('silver',3,6,'{}',0,3717.39,557.61,4275), ('silver',6,12,'{}',0,7043.48,1056.52,8100), ('silver',12,24,'{}',0,13304.35,1995.65,15300),
  ('gold',3,9,'{"reshare_quote":3,"pin":1}',0,5565.22,834.78,6400), ('gold',6,18,'{"reshare_quote":6,"pin":2}',0,10565.22,1584.78,12150), ('gold',12,36,'{"reshare_quote":12,"pin":4}',0,19956.52,2993.48,22950),
  ('platinum',3,12,'{"reshare_quote":6,"pin":3,"paid_campaign":3}',300,7434.78,1115.22,8550), ('platinum',6,24,'{"reshare_quote":12,"pin":6,"paid_campaign":6}',300,14086.96,2113.04,16200), ('platinum',12,48,'{"reshare_quote":24,"pin":12,"paid_campaign":12}',300,26608.70,3991.30,30600),
  ('corporate',3,18,'{"reshare_quote":12,"pin":6,"paid_campaign":6}',300,15652.17,2347.83,18000), ('corporate',6,36,'{"reshare_quote":24,"pin":12,"paid_campaign":12}',300,29739.13,4460.87,34200), ('corporate',12,72,'{"reshare_quote":48,"pin":24,"paid_campaign":24}',300,56347.83,8452.17,64800);

ALTER TABLE public.membership_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_plan_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_credit_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_benefit_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_credit_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_benefit_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_request_benefits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_agreements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Active membership plans are public" ON public.membership_plans FOR SELECT TO anon, authenticated USING (active);
CREATE POLICY "Active membership prices are public" ON public.membership_plan_prices FOR SELECT TO anon, authenticated USING (active);
CREATE POLICY "Members can view own memberships" ON public.memberships FOR SELECT TO authenticated USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "Members can view own credit wallet" ON public.membership_credit_wallets FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.memberships m WHERE m.id = membership_id AND m.user_id = (SELECT auth.uid())));
CREATE POLICY "Members can view own benefit wallets" ON public.membership_benefit_wallets FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.memberships m WHERE m.id = membership_id AND m.user_id = (SELECT auth.uid())));
CREATE POLICY "Members can view own credit ledger" ON public.membership_credit_ledger FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.memberships m WHERE m.id = membership_id AND m.user_id = (SELECT auth.uid())));
CREATE POLICY "Members can view own benefit ledger" ON public.membership_benefit_ledger FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.memberships m WHERE m.id = membership_id AND m.user_id = (SELECT auth.uid())));
CREATE POLICY "Members can view own requested benefits" ON public.membership_request_benefits FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.memberships m WHERE m.id = membership_id AND m.user_id = (SELECT auth.uid())));
CREATE POLICY "Members can view own payments" ON public.membership_payments FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.memberships m WHERE m.id = membership_id AND m.user_id = (SELECT auth.uid())));
CREATE POLICY "Members can view own agreements" ON public.membership_agreements FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.memberships m WHERE m.id = membership_id AND m.user_id = (SELECT auth.uid())));

GRANT SELECT ON public.membership_plans, public.membership_plan_prices TO anon, authenticated;
GRANT SELECT ON public.memberships, public.membership_credit_wallets, public.membership_benefit_wallets,
  public.membership_credit_ledger, public.membership_benefit_ledger, public.membership_payments,
  public.membership_request_benefits, public.membership_agreements TO authenticated;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('membership-contracts', 'membership-contracts', false, 10485760, ARRAY['application/pdf'])
ON CONFLICT (id) DO UPDATE SET public = false, file_size_limit = 10485760, allowed_mime_types = ARRAY['application/pdf'];

CREATE OR REPLACE FUNCTION public.activate_membership(
  p_membership_id uuid, p_provider text, p_provider_payment_id text, p_provider_response jsonb DEFAULT NULL
) RETURNS public.memberships
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_membership public.memberships;
  v_price public.membership_plan_prices;
  v_wallet public.membership_credit_wallets;
  v_start timestamptz := now();
  v_benefit record;
BEGIN
  SELECT * INTO v_membership FROM public.memberships WHERE id = p_membership_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'membership_not_found'; END IF;
  IF v_membership.status = 'active' AND v_membership.payment_status = 'paid' THEN RETURN v_membership; END IF;
  IF v_membership.status NOT IN ('pending_payment', 'payment_review') THEN RAISE EXCEPTION 'membership_not_payable'; END IF;
  SELECT * INTO v_price FROM public.membership_plan_prices WHERE id = v_membership.plan_price_id AND active;
  IF NOT FOUND THEN RAISE EXCEPTION 'membership_plan_unavailable'; END IF;

  UPDATE public.memberships SET status='active', payment_status='paid', payment_provider=p_provider,
    moyasar_payment_id=CASE WHEN p_provider='moyasar' THEN p_provider_payment_id ELSE moyasar_payment_id END,
    tamara_order_id=CASE WHEN p_provider='tamara' THEN p_provider_payment_id ELSE tamara_order_id END,
    paid_at=COALESCE(paid_at,now()), starts_at=COALESCE(starts_at,v_start),
    ends_at=COALESCE(ends_at,v_start + make_interval(months => duration_months)), updated_at=now()
  WHERE id=p_membership_id RETURNING * INTO v_membership;

  INSERT INTO public.membership_credit_wallets (membership_id,total_credits,expires_at)
  VALUES (v_membership.id,v_price.included_credits,v_membership.ends_at)
  ON CONFLICT (membership_id) DO NOTHING RETURNING * INTO v_wallet;
  IF v_wallet.id IS NULL THEN SELECT * INTO v_wallet FROM public.membership_credit_wallets WHERE membership_id=v_membership.id; END IF;
  INSERT INTO public.membership_credit_ledger (membership_id,wallet_id,transaction_type,credits,note,idempotency_key)
  VALUES (v_membership.id,v_wallet.id,'grant',v_price.included_credits,'إضافة رصيد العضوية الكامل','grant:'||v_membership.id::text)
  ON CONFLICT (idempotency_key) DO NOTHING;

  FOR v_benefit IN SELECT key, value::integer AS units FROM jsonb_each_text(v_price.benefit_entitlements) LOOP
    IF v_benefit.units > 0 THEN
      INSERT INTO public.membership_benefit_wallets (membership_id,benefit_type,total_units,unit_budget,expires_at)
      VALUES (v_membership.id,v_benefit.key,v_benefit.units,
        CASE WHEN v_benefit.key='paid_campaign' THEN v_price.ad_budget_per_30_days ELSE 0 END,v_membership.ends_at)
      ON CONFLICT (membership_id,benefit_type) DO NOTHING;
    END IF;
  END LOOP;

  INSERT INTO public.membership_payments (membership_id,provider,provider_payment_id,amount,status,provider_response,paid_at)
  VALUES (v_membership.id,p_provider,p_provider_payment_id,v_membership.total_amount,'paid',p_provider_response,now())
  ON CONFLICT (provider,provider_payment_id) WHERE provider_payment_id IS NOT NULL
  DO UPDATE SET status='paid',provider_response=EXCLUDED.provider_response,paid_at=COALESCE(public.membership_payments.paid_at,EXCLUDED.paid_at),updated_at=now();
  INSERT INTO public.membership_agreements (membership_id,version,terms_snapshot,accepted_at,accepted_ip,accepted_user_agent)
  VALUES (v_membership.id,v_membership.terms_version,v_membership.terms_snapshot,v_membership.terms_accepted_at,v_membership.acceptance_ip,v_membership.acceptance_user_agent)
  ON CONFLICT (membership_id,version) DO NOTHING;
  RETURN v_membership;
END; $$;

CREATE OR REPLACE FUNCTION public.reserve_membership_credit(
  p_membership_id uuid, p_request_id uuid, p_credits integer DEFAULT 1
) RETURNS public.membership_credit_wallets
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_membership public.memberships; v_plan public.membership_plans;
  v_wallet public.membership_credit_wallets; v_active_requests integer;
BEGIN
  IF p_credits <= 0 THEN RAISE EXCEPTION 'invalid_credit_amount'; END IF;
  SELECT * INTO v_membership FROM public.memberships WHERE id=p_membership_id FOR UPDATE;
  IF NOT FOUND OR v_membership.status<>'active' OR now()<v_membership.starts_at OR now()>=v_membership.ends_at THEN RAISE EXCEPTION 'membership_inactive'; END IF;
  SELECT * INTO v_plan FROM public.membership_plans WHERE id=v_membership.plan_id AND active;
  SELECT * INTO v_wallet FROM public.membership_credit_wallets WHERE membership_id=v_membership.id FOR UPDATE;
  IF NOT FOUND OR v_wallet.expires_at<=now() THEN RAISE EXCEPTION 'membership_wallet_unavailable'; END IF;
  SELECT count(*) INTO v_active_requests FROM public.publish_requests WHERE membership_id=v_membership.id AND id<>p_request_id
    AND status NOT IN ('completed','rejected','client_rejected','cancelled','auto_closed','refunded');
  IF v_active_requests>=v_plan.concurrent_request_limit THEN RAISE EXCEPTION 'membership_concurrent_limit'; END IF;
  IF v_wallet.total_credits-v_wallet.reserved_credits-v_wallet.used_credits<p_credits THEN RAISE EXCEPTION 'membership_insufficient_credits'; END IF;
  UPDATE public.membership_credit_wallets SET reserved_credits=reserved_credits+p_credits,updated_at=now() WHERE id=v_wallet.id RETURNING * INTO v_wallet;
  UPDATE public.publish_requests SET billing_source='membership',membership_id=v_membership.id,membership_wallet_id=v_wallet.id,
    membership_credits=p_credits,membership_credit_status='reserved',updated_at=now() WHERE id=p_request_id;
  INSERT INTO public.membership_credit_ledger (membership_id,wallet_id,request_id,transaction_type,credits,note,idempotency_key)
  VALUES (v_membership.id,v_wallet.id,p_request_id,'reserve',-p_credits,'حجز رصيد لطلب جديد','reserve:'||p_request_id::text)
  ON CONFLICT (idempotency_key) DO NOTHING;
  RETURN v_wallet;
END; $$;

CREATE OR REPLACE FUNCTION public.consume_membership_credit(p_request_id uuid) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_request public.publish_requests;
BEGIN
  SELECT * INTO v_request FROM public.publish_requests WHERE id=p_request_id FOR UPDATE;
  IF NOT FOUND OR v_request.billing_source<>'membership' OR v_request.membership_credit_status='consumed' THEN RETURN; END IF;
  IF v_request.membership_credit_status<>'reserved' THEN RAISE EXCEPTION 'membership_credit_not_reserved'; END IF;
  UPDATE public.membership_credit_wallets SET reserved_credits=reserved_credits-v_request.membership_credits,
    used_credits=used_credits+v_request.membership_credits,updated_at=now() WHERE id=v_request.membership_wallet_id;
  UPDATE public.publish_requests SET membership_credit_status='consumed',updated_at=now() WHERE id=p_request_id;
  INSERT INTO public.membership_credit_ledger (membership_id,wallet_id,request_id,transaction_type,credits,note,idempotency_key)
  VALUES (v_request.membership_id,v_request.membership_wallet_id,p_request_id,'consume',-v_request.membership_credits,'بدء التنفيذ واستهلاك الرصيد','consume:'||p_request_id::text)
  ON CONFLICT (idempotency_key) DO NOTHING;
END; $$;

CREATE OR REPLACE FUNCTION public.release_membership_credit(p_request_id uuid,p_note text DEFAULT NULL) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_request public.publish_requests;
BEGIN
  SELECT * INTO v_request FROM public.publish_requests WHERE id=p_request_id FOR UPDATE;
  IF NOT FOUND OR v_request.billing_source<>'membership' OR v_request.membership_credit_status<>'reserved' THEN RETURN; END IF;
  UPDATE public.membership_credit_wallets SET reserved_credits=reserved_credits-v_request.membership_credits,updated_at=now() WHERE id=v_request.membership_wallet_id;
  UPDATE public.publish_requests SET membership_credit_status='released',updated_at=now() WHERE id=p_request_id;
  INSERT INTO public.membership_credit_ledger (membership_id,wallet_id,request_id,transaction_type,credits,note,idempotency_key)
  VALUES (v_request.membership_id,v_request.membership_wallet_id,p_request_id,'release',v_request.membership_credits,COALESCE(p_note,'إعادة الرصيد المحجوز'),'release:'||p_request_id::text)
  ON CONFLICT (idempotency_key) DO NOTHING;
END; $$;

CREATE OR REPLACE FUNCTION public.reserve_membership_benefits(p_request_id uuid,p_benefits jsonb) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_request public.publish_requests; v_type text; v_wallet public.membership_benefit_wallets;
BEGIN
  SELECT * INTO v_request FROM public.publish_requests WHERE id=p_request_id AND billing_source='membership' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'membership_request_not_found'; END IF;
  FOR v_type IN SELECT jsonb_array_elements_text(COALESCE(p_benefits,'[]'::jsonb)) LOOP
    IF v_type NOT IN ('reshare_quote','pin','paid_campaign') THEN RAISE EXCEPTION 'invalid_membership_benefit'; END IF;
    SELECT * INTO v_wallet FROM public.membership_benefit_wallets
      WHERE membership_id=v_request.membership_id AND benefit_type=v_type AND expires_at>now() FOR UPDATE;
    IF NOT FOUND OR v_wallet.total_units-v_wallet.reserved_units-v_wallet.used_units<1 THEN RAISE EXCEPTION 'membership_benefit_unavailable:%',v_type; END IF;
    UPDATE public.membership_benefit_wallets SET reserved_units=reserved_units+1,updated_at=now() WHERE id=v_wallet.id;
    INSERT INTO public.membership_request_benefits (membership_id,request_id,wallet_id,benefit_type)
      VALUES (v_request.membership_id,p_request_id,v_wallet.id,v_type) ON CONFLICT (request_id,benefit_type) DO NOTHING;
    INSERT INTO public.membership_benefit_ledger (membership_id,wallet_id,request_id,transaction_type,units,note,idempotency_key)
      VALUES (v_request.membership_id,v_wallet.id,p_request_id,'reserve',-1,'حجز ميزة للطلب','benefit-reserve:'||p_request_id::text||':'||v_type)
      ON CONFLICT (idempotency_key) DO NOTHING;
  END LOOP;
END; $$;

CREATE OR REPLACE FUNCTION public.consume_membership_benefits(p_request_id uuid) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_item public.membership_request_benefits;
BEGIN
  FOR v_item IN SELECT * FROM public.membership_request_benefits WHERE request_id=p_request_id AND status='reserved' FOR UPDATE LOOP
    UPDATE public.membership_benefit_wallets SET reserved_units=reserved_units-v_item.units,used_units=used_units+v_item.units,updated_at=now() WHERE id=v_item.wallet_id;
    UPDATE public.membership_request_benefits SET status='consumed',updated_at=now() WHERE id=v_item.id;
    INSERT INTO public.membership_benefit_ledger (membership_id,wallet_id,request_id,transaction_type,units,note,idempotency_key)
      VALUES (v_item.membership_id,v_item.wallet_id,p_request_id,'consume',-v_item.units,'بدء تنفيذ ميزة الطلب','benefit-consume:'||p_request_id::text||':'||v_item.benefit_type)
      ON CONFLICT (idempotency_key) DO NOTHING;
  END LOOP;
END; $$;

CREATE OR REPLACE FUNCTION public.release_membership_benefits(p_request_id uuid,p_note text DEFAULT NULL) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_item public.membership_request_benefits;
BEGIN
  FOR v_item IN SELECT * FROM public.membership_request_benefits WHERE request_id=p_request_id AND status='reserved' FOR UPDATE LOOP
    UPDATE public.membership_benefit_wallets SET reserved_units=reserved_units-v_item.units,updated_at=now() WHERE id=v_item.wallet_id;
    UPDATE public.membership_request_benefits SET status='released',updated_at=now() WHERE id=v_item.id;
    INSERT INTO public.membership_benefit_ledger (membership_id,wallet_id,request_id,transaction_type,units,note,idempotency_key)
      VALUES (v_item.membership_id,v_item.wallet_id,p_request_id,'release',v_item.units,COALESCE(p_note,'إعادة رصيد الميزة'),'benefit-release:'||p_request_id::text||':'||v_item.benefit_type)
      ON CONFLICT (idempotency_key) DO NOTHING;
  END LOOP;
END; $$;

REVOKE ALL ON FUNCTION public.activate_membership(uuid,text,text,jsonb) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.reserve_membership_credit(uuid,uuid,integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.consume_membership_credit(uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.release_membership_credit(uuid,text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.reserve_membership_benefits(uuid,jsonb) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.consume_membership_benefits(uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.release_membership_benefits(uuid,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.activate_membership(uuid,text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.reserve_membership_credit(uuid,uuid,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.consume_membership_credit(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_membership_credit(uuid,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.reserve_membership_benefits(uuid,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.consume_membership_benefits(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_membership_benefits(uuid,text) TO service_role;
